### PR TITLE
Perform modified retry on JWT auth

### LINKED ISSUE #475: Started getting api status 400 error suddenly - `Please check the 'jti' claim.`
We are on 

`com.box:box-java-sdk:2.4.0`

We have CI servers that run some very small tests that use integration tests that utilize read-only Box.com. This CI box test, after working for a long time with no problems, suddenly started giving us this error:

`{error:invalid_grant,error_description: Please check the 'jti' claim.}`

What might this be?

### LINKED ISSUE #519: Generate new jti claim when retrying JWT auth request
In order to prevent auth errors, the jti claim in the JWT needs to be regenerated before the auth request is retried — otherwise it might already be in the replay prevention cache, causing the retry to fail with a 400.

### PR DESCRIPTION
**Pull request by mattwiller**
If JWT auth fails, attempt a manual retry that:
1. Regenerates the `jti` claim to avoid scenarios where the JWT ID was already consumed
2. Uses the Date header from the API response to calculate the JWT `exp` claim, to avoid issues related to clock drift

Fixes #519
Fixes #475

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @mattwiller has signed the CLA. Thanks for the pull request!

File: src/test/java/com/box/sdk/BoxDeveloperEditionAPIConnectionTest.java [hunk 1]
```diff
@@ -0,0 +1,192 @@
...
+        api.setBaseURL(baseURL + "/");
+        api.setTokenURL(baseURL + tokenPath);
+        api.setMaxRequestAttempts(1);
+
+        final String[] jtiClaims = new String[1];
+
+
+        this.wireMockRule.stubFor(post(urlPathMatching(tokenPath))
+            .atPriority(1)
+            .withPostServeAction("save-jti", new Parameters())
```
Comment (carycheng) [inline src/test/java/com/box/sdk/BoxDeveloperEditionAPIConnectionTest.java]: Please remove

File: src/test/java/com/box/sdk/BoxDeveloperEditionAPIConnectionTest.java [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+                    long expTimestamp = claims.getExpirationTime().getValue();
+
+                    Assert.assertEquals("JWT should have the expected timestamp", 1511003940L, expTimestamp);
+                    Assert.assertNotEquals("JWT should have a new jti claim",
+                            BoxDeveloperEditionAPIConnectionTest.this.jtiClaim, jti);
+
+                } catch (AssertionFailedError ex) {
+                    throw ex;
+                } catch (Exception ex) {
+                    Assert.fail("Could not parse JWT when request is retried: " + ex.getMessage());
```
Comment (carycheng) [inline src/test/java/com/box/sdk/BoxDeveloperEditionAPIConnectionTest.java]: return here
