### PR TITLE
Fixes #67, Fixes #68, Fixes #69 - Metadata feedback and fixes

### LINKED ISSUE #67: Metadata integration tests fail
When metadata is set in `createMetadataSucceeds()` and `updateMetadataSucceeds()` in `BoxFileTest`, there's no leading slash which causes the key to be set as `oo` instead of `foo`.

```java
uploadedFile.createMetadata(new Metadata().add("foo", "bar"));
```

should be

```java
uploadedFile.createMetadata(new Metadata().add("/foo", "bar"));
```

### LINKED ISSUE #68: Metadata get(String) method should take a path instead of a key
The `Metadata.get(String)` method should take a path so that nested metadata keys can be retrieved. It will also make it consistent with the add, test, replace, and remove methods.

### LINKED ISSUE #69: Metadata class shouldn't throw NPE for missing keys
The `getID()`, `getTypeName()`, and `getParentID()` methods can possibly throw a NPE if an empty metadata object is created. Similarly, the `get(String)` method will throw an exception if a requested key doesn't exist. This is because `this.values.get("some-key")` returns null and then `asString()` gets called on it.

These methods should do null checks before calling `asString()` and return null if the key doesn't exist.

### PR DESCRIPTION
**Pull request by codyebberson**
Now using the "/path" format for all operations, including get().

Handling missing values more gracefully, returning null.

Fixed bug in integration tests.

Added a bunch of unit tests to catch key vs. path problems.

### CODE REVIEW

**Comment by boxcla** [comment]
Verified that @codyebberson has signed the CLA. Thanks for the pull request!

File: src/main/java/com/box/sdk/Metadata.java [hunk 1]
```diff
@@ -142,6 +147,9 @@ public String toString() {
      * @return the JSON property name.
      */
     private String pathToProperty(String path) {
+        if (path == null || !path.startsWith("/")) {
+            throw new IllegalArgumentException("Path must be prefixed with a \"/\".");
```
Comment (gcurtis) [inline src/main/java/com/box/sdk/Metadata.java]: I like this idea of throwing an IllegalArgumentException for invalid paths.

File: src/test/java/com/box/sdk/MetadataTest.java [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+    @Category(UnitTest.class)
+    public void testNullPath() {
+        try {
+            new Metadata().add(null, "value");
+            Assert.fail("Expected IllegalArgumentException");
+        } catch (IllegalArgumentException ex) {
+        }
+    }
+
+    @Test
```
Comment (gcurtis) [inline src/test/java/com/box/sdk/MetadataTest.java]: You can also do `@Test(expected=IllegalArgumentException.class)` to make it a bit clearer that you're testing that an exception is being thrown. It'll also let you get rid of the try/catch and the `Assert.fail()`.

Comment (codyebberson) [inline src/test/java/com/box/sdk/MetadataTest.java]: Yeah...  Using "expected" causes problems for EclEmma (code coverage tool), so I try to avoid it.  If that's your preference, I'm happy to make the change.

**Comment by gcurtis** [comment]
Thanks for fixing these! Just left one suggestion about expecting the `IlegalArgumentException` in the unit test.
